// <auto-generated />
using System;
using FuncionarioApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FuncionarioApi.Migrations
{
    [DbContext(typeof(FuncionarioDbContext))]
    partial class FuncionarioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("FuncionarioApi.Data.Entities.FuncionarioEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Documento")
                        .HasColumnType("longtext");

                    b.Property<bool>("HasPlanoDental")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasPlanoSaude")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasValeTransporte")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<double>("SalarioBruto")
                        .HasColumnType("double");

                    b.Property<string>("Setor")
                        .HasColumnType("longtext");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
